// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg1dI0bDXHrdJR5k8JagJb-wQrB9Rxqok',
    appId: '1:1037818432676:web:2b8072477f51aa59652a31',
    messagingSenderId: '1037818432676',
    projectId: 'school-management-593ef',
    authDomain: 'school-management-593ef.firebaseapp.com',
    databaseURL: 'https://school-management-593ef-default-rtdb.firebaseio.com',
    storageBucket: 'school-management-593ef.firebasestorage.app',
    measurementId: 'G-VVSVV7H67Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKmWmlPO1y_PMTTEUYnum4wYAMaCxJHCA',
    appId: '1:1037818432676:android:3d6aeddeceab35b7652a31',
    messagingSenderId: '1037818432676',
    projectId: 'school-management-593ef',
    databaseURL: 'https://school-management-593ef-default-rtdb.firebaseio.com',
    storageBucket: 'school-management-593ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnv9PGVdc8TDkvCJuQSAzDYrkmBqm830k',
    appId: '1:1037818432676:ios:1016715882c4d6d1652a31',
    messagingSenderId: '1037818432676',
    projectId: 'school-management-593ef',
    databaseURL: 'https://school-management-593ef-default-rtdb.firebaseio.com',
    storageBucket: 'school-management-593ef.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnv9PGVdc8TDkvCJuQSAzDYrkmBqm830k',
    appId: '1:1037818432676:ios:1016715882c4d6d1652a31',
    messagingSenderId: '1037818432676',
    projectId: 'school-management-593ef',
    databaseURL: 'https://school-management-593ef-default-rtdb.firebaseio.com',
    storageBucket: 'school-management-593ef.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg1dI0bDXHrdJR5k8JagJb-wQrB9Rxqok',
    appId: '1:1037818432676:web:426703edd8d7a1af652a31',
    messagingSenderId: '1037818432676',
    projectId: 'school-management-593ef',
    authDomain: 'school-management-593ef.firebaseapp.com',
    databaseURL: 'https://school-management-593ef-default-rtdb.firebaseio.com',
    storageBucket: 'school-management-593ef.firebasestorage.app',
    measurementId: 'G-Z2XL1RFJZE',
  );
}
